### PR TITLE
feat: add support for `tsimp`

### PR DESCRIPTION
**Pull request by stuft2**
Adds support for loading TypeScript plugins via [`tsimp`](https://github.com/tapjs/tsimp).

Due to the fact that Node.js versions older than v20 are no longer supported in Fastify v5, I chose not to implement support for the alternate loader script (i.e. --loader=tsimp/loader) that `tsimp` provides.

> [!CAUTION]
> `tsimp` currently has an [open issue](https://github.com/tapjs/tsimp/issues/29) and [corresponding PR](https://github.com/tapjs/tsimp/pull/30) to fix a bug limiting TypeScript support to version 5.5 or earlier (the latest version of TypeScript is v5.6.2). I'm happy to wait on this PR until the `tsimp` bug is fixed, at which point I will update the TypeScript and `tsimp` versions.

#### Checklist

- [x] run `npm run test` and `npm run benchmark`
- [x] tests and/or benchmarks are included
- [x] documentation is changed or added
- [x] commit message and code follows the [Developer's Certification of Origin](https://github.com/fastify/.github/blob/master/CONTRIBUTING.md#developers-certificate-of-origin-11)
      and the [Code of conduct](https://github.com/fastify/.github/blob/master/CODE_OF_CONDUCT.md)

### CODE REVIEW

**Review by Uzlopak — APPROVED** [review]
LGTM

**Comment by stuft2** [comment]
Would you rather wait for tsimp to fix their typescript bug or does it not matter to you since it's a dev dependency?

**Comment by Uzlopak** [comment]
Imho irrelevant for us.i never heard of tsimp, so i let others decide if it is relevant or not. But codewise i think it is acceptable.

**Review by mcollina — APPROVED** [review]
lgtm

**Comment by mcollina** [comment]
Tests are passing, this can land

**Pull request merged**
