### PR TITLE
Fix dependencies across directories

### PR DESCRIPTION
**Pull request by mcollina**
Fixes a regression introduced in https://github.com/fastify/fastify-autoload/pull/401 where `dependencies` across different prefixes were not taken into account.

### CODE REVIEW

**Review by jean-michelet — COMMENTED** [review]
Looks good, but is it possible to write a test that proves the bug is fixed? And to avoid same regression in the future?

**Comment by jean-michelet** [comment]
If too cumbersome to write, but you're sure the bug is fixed, I recommend to merge and create an issue to write this test and you assign to me.

**Comment by mcollina** [comment]
> Looks good, but is it possible to write a test that proves the bug is fixed? And to avoid same regression in the future?

It's covered by moving the file `plugin-d.js` as you can see in the diff.

**Comment by jean-michelet** [comment]
Ok, missed it.

**Review by jean-michelet — APPROVED** [review]

**Pull request merged**
