### PR TITLE
fix: set routeParamPattern to global (issue #171)

### PR DESCRIPTION
**Pull request by arthur-fontaine**
#### Checklist

- [x] run `npm run test` and `npm run benchmark`
- [x] tests and/or benchmarks are included
- [ ] documentation is changed or added
- [x] commit message and code follows the [Developer's Certification of Origin](https://github.com/fastify/.github/blob/master/CONTRIBUTING.md#developers-certificate-of-origin-11)
      and the [Code of conduct](https://github.com/fastify/.github/blob/master/CODE_OF_CONDUCT.md)

### CODE REVIEW

**Review by mcollina — CHANGES_REQUESTED** [review]
Can you please add a unit test?

**Review by mcollina — APPROVED** [review]
lgtm

**Review by RafaelGSS — COMMENTED** [review]
Any reason for the tests is under typescript-jest?

**Comment by arthur-fontaine** [comment]
because I prefer Jest than others one. did I had to write the unit test in another directory?

**Comment by RafaelGSS** [comment]
> because I am more comfortable with Jest than others one. did I had to write the test in another directory?

I guess that the `typescript-jest` is a test to validate integration with `jest`. The core tests were written using tap. Correct me if I'm the wrong @mcollina.

**Comment by mcollina** [comment]
Yes, that's true.

**Comment by arthur-fontaine** [comment]
In which directory do I have to write the tests?

**Comment by RafaelGSS** [comment]
`tests/commonjs` is suitable. Let me know if you need some help with it.

**Review by RafaelGSS — APPROVED** [review]
LGTM.

**Comment by arthur-fontaine** [comment]
f* sorry I missclicked :(

**Review by RafaelGSS — APPROVED** [review]
LGTM.

**Review by mcollina — APPROVED** [review]
lgtm

**Pull request merged**
