### PR TITLE
fix: add missing type routeParams

### PR DESCRIPTION
**Pull request by arthur-fontaine**
related to #134

### CODE REVIEW

**Review by climba03003 — COMMENTED** [review]
Can you add an unit test for this option in typescript ?

**Comment by arthur-fontaine** [comment]
I can try but I have never written a test before...

**Comment by Eomm** [comment]
> I can try but I have never written a test before...

YOu may take inspiration from the tests already in place in this folder:
https://github.com/fastify/fastify-autoload/blob/master/test/typescript/

**Comment by arthur-fontaine** [comment]
I don't know if the only changes I've written are enough... 
[the commit](https://github.com/fastify/fastify-autoload/pull/153/commits/1683d569d28b03b8b9fbc952b690b07e160a1418)

**Review by climba03003 — APPROVED** [review]
LGTM.

**Review by RafaelGSS — APPROVED** [review]
LGTM.

**Review by mcollina — APPROVED** [review]
lgtm

**Pull request merged**
