### PR TITLE
test: add test for env integration

### LINKED ISSUE #102: Create tests for ts-node and ts-node-dev
Reference: #100 

We discover that our tests not cover some tools, so, is important to create tests that cover `ts-node` and `ts-node-dev` tool.

### PR DESCRIPTION
**Pull request by climba03003**
Resolve #102 
I do not know if it is the right approach for testing ```ts-node``` and ```ts-node-dev``` integration. But I think it is the only way to see if it is working properly.

The two test case increase the test time from 1S to 8S and I think it is not worth for such two test case.

#### Checklist

- [x] run `npm run test` and `npm run benchmark`
- [x] tests and/or benchmarks are included
- [ ] documentation is changed or added
- [x] commit message and code follows the [Developer's Certification of Origin](https://github.com/fastify/.github/blob/master/CONTRIBUTING.md#developers-certificate-of-origin-11)
      and the [Code of conduct](https://github.com/fastify/.github/blob/master/CODE_OF_CONDUCT.md)

### CODE REVIEW

**Comment by mcollina** [comment]
are those needed to be jest-tests? I think these can get better with tap (as they'd run in parallel). I would also recommend using spawn instead of spawnSync and keep things asynchronous.

**Comment by climba03003** [comment]
> 
> 
> are those needed to be jest-tests? I think these can get better with tap (as they'd run in parallel). I would also recommend using spawn instead of spawnSync and keep things asynchronous.

I can use tap for the ```ts-node``` test.
however, the ```ts-node-dev``` always error when using ```tap```

```
test/typescript/integration.ts 1>     Ignore watch: []
test/typescript/integration.ts 1>     [INFO] 22:32:09 ts-node-dev ver. 1.1.1 (using ts-node ver. 9.1.1, typescript ver. 3.9.7)
test/typescript/integration.ts 1>     [DEBUG] 22:32:09 Starting child process -r /tmp/ts-node-dev-hook-060858551201929734.js /fastify-autoload/node_modules/ts-node-dev/lib/wrap.js /fastify-autoload/test/typescript/basic/ts-node-dev.ts
test/typescript/integration.ts 1>     [DEBUG] 22:32:09 /fastify-autoload/test/typescript/basic/ts-node-dev.ts added to watcher
test/typescript/integration.ts 1>     [DEBUG] 22:32:11 /fastify-autoload/test/typescript/basic/ts-node-dev.ts compiled in 1595 ms
test/typescript/integration.ts 2> RangeError: Maximum call stack size exceeded
test/typescript/integration.ts 2>     at stringify (<anonymous>)
test/typescript/integration.ts 2>     at writeChannelMessage (internal/child_process/serialization.js:117:20)
test/typescript/integration.ts 2>     at process.target._send (internal/child_process.js:804:17)
test/typescript/integration.ts 2>     at process.target.send (internal/child_process.js:702:19)
test/typescript/integration.ts 2>     at Object.exports.send (/fastify-autoload/node_modules/ts-node-dev/lib/ipc.js:17:14)
test/typescript/integration.ts 2>     at /fastify-autoload/node_modules/ts-node-dev/lib/wrap.js:88:9
test/typescript/integration.ts 2>     at nodeDevHook (/fastify-autoload/node_modules/ts-node-dev/lib/hook.js:61:17)
test/typescript/integration.ts 2>     at /fastify-autoload/node_modules/append-transform/index.js:62:4
test/typescript/integration.ts 2>     at nodeDevHook (/fastify-autoload/node_modules/ts-node-dev/lib/hook.js:63:13)
test/typescript/integration.ts 2>     at /fastify-autoload/node_modules/append-transform/index.js:62:4
test/typescript/integration.ts 1>     [DEBUG] 22:32:11 Child error
test/typescript/integration.ts 1>     [ERROR] 22:32:11 RangeError: Maximum call stack size exceeded
test/typescript/integration.ts 1>     [DEBUG] 22:32:11 Disconnecting from child
test/typescript/integration.ts 1>     [DEBUG] 22:32:11 Sending SIGTERM kill to child pid 18281
test/typescript/integration.ts 1>     [DEBUG] 22:32:11 Child exited with code 0
```

**Review by mcollina — APPROVED** [review]
lgtm

**Comment by climba03003** [comment]
this PR is ignored in space.

**Comment by mcollina** [comment]
Sorry for the delay, I hoped somebody else would take a look

**Pull request merged**
