### PR TITLE
add snippet to allow loading multiple directories with one call

### PR DESCRIPTION
**Pull request by ferco0**
Like this:
```js
...
app.register(autoLoad, [
  { dir: join(__dirname, 'plugins')},
  { dir: join(__dirname, 'routes')},
])
....
```
#### Checklist

- [x] run `npm run test` and `npm run benchmark`
- [x] tests and/or benchmarks are included // I think this don't need a test.
- [x] documentation is changed or added
- [x] commit message and code follows [Code of conduct](https://github.com/fastify/fastify/blob/master/CODE_OF_CONDUCT.md)

### CODE REVIEW

**Comment by ferco0** [comment]
Thanks! would it be good to have the both ways?

**Comment by mcollina** [comment]
I don't really understand the need.. if you need to pass different options, why do it when you can issue two register calls?

**Comment by ferco0** [comment]
For example: If, for any reason, we need a different ignore pattern for each directory or different prefix.

**Comment by mcollina** [comment]
Why is doing multiple `app.register(autoload)` not possible then?

**Comment by ferco0** [comment]
does, but why not by an array? is ready and anyone could prefer it like that, I would prefer. I like to avoid method calls as much as I can in the application code.

**Comment by mcollina** [comment]
I do not think this is needed.

**Comment by ferco0** [comment]
could be a performance increase, avoiding fastify.register call?

**Comment by mcollina** [comment]
not really, that's pretty cheap

**Pull request closed without merging**
