### PR TITLE
fix: allow package.json in the root of autoload dir (#188)

### PR DESCRIPTION
**Pull request by thebearingedge**
Not really sure what `npm run benchmark` was supposed to do. There's no script for it.

#### Checklist

- [x] run `npm run test` and `npm run benchmark`
- [x] tests and/or benchmarks are included
- [ ] documentation is changed or added
- [x] commit message and code follows the [Developer's Certification of Origin](https://github.com/fastify/.github/blob/master/CONTRIBUTING.md#developers-certificate-of-origin-11)
      and the [Code of conduct](https://github.com/fastify/.github/blob/master/CODE_OF_CONDUCT.md)

Thank you! Please lemme know if I need to do anything else or if I'm misunderstanding how the package works 😂 .

### CODE REVIEW

**Review by mcollina — APPROVED** [review]
lgtm, thanks!

**Review by Eomm — COMMENTED** [review]
CI is failing

Could you take a look?

**Comment by thebearingedge** [comment]
@Eomm No problem, I believe it's fixed now. The workflows passed on my fork and are ready to be re-run.

**Review by Eomm — APPROVED** [review]

**Comment by Eomm** [comment]
Fixes https://github.com/fastify/fastify-autoload/issues/188

**Pull request merged**
