### PR TITLE
fix: ci should run on the matrix os

### PR DESCRIPTION
**Pull request by simoneb**
It was running always on ubuntu despite the matrix config

### CODE REVIEW

**Review by zekth — APPROVED** [review]
good catch

**Comment by simoneb** [comment]
> good catch

Eh, this needs fixing to run on Windows now though

**Comment by zekth** [comment]
> > good catch
> 
> Eh, this needs fixing to run on Windows now though

indeed.

**Comment by simoneb** [comment]
> > > good catch
> > 
> > 
> > Eh, this needs fixing to run on Windows now though
> 
> indeed.

done with a node script. now there are two windows-specific failures in integration tests. having a look at that too

**Comment by simoneb** [comment]
fixed

**Review by climba03003 — APPROVED** [review]

**Review by zekth — APPROVED** [review]

**Review by RafaelGSS — APPROVED** [review]
LGTM.

**Review by mcollina — APPROVED** [review]
lgtm

**Pull request merged**
