### PR TITLE
Added support for ts-node-dev

### PR DESCRIPTION
**Pull request by MichielDeMey**
This PR adds support for [ts-node-dev](https://github.com/whitecolor/ts-node-dev) which uses `ts-node` under the hood.
Tested and verified working on my local machine.

From the `ts-node-dev` docs:
> If you need to detect that you are running with ts-node-dev, check if process.env.TS_NODE_DEV is set.

AFAIK, no documentation changes are required as TypeScript is supported out-of-the-box by this module.

#### Checklist

- [x] run `npm run test` and `npm run benchmark`
- [ ] tests and/or benchmarks are included
- [ ] documentation is changed or added
- [ ] commit message and code follows the [Developer's Certification of Origin](https://github.com/fastify/.github/blob/master/CONTRIBUTING.md#developers-certificate-of-origin-11)
      and the [Code of conduct](https://github.com/fastify/.github/blob/master/CODE_OF_CONDUCT.md)

### CODE REVIEW

**Comment by RafaelGSS** [comment]
Could you add a test for it?

**Comment by MichielDeMey** [comment]
Any pointers on how to write tests for this?
Couldn't find a test for the original `ts-node` support in the repo. Might have overlooked it.

**Comment by mcollina** [comment]
ts-node is checked via tap typescript support

**Comment by MichielDeMey** [comment]
> ts-node is checked via tap typescript support

Does this mean that TypeScript is already tested regardless of running through `ts-node`, `ts-node-dev` or others? 🤔

**Comment by mcollina** [comment]
well, definitely not on ts-node-dev, otherwise it would have worked!

**Comment by MichielDeMey** [comment]
Hence this PR. 🙂 

But honestly, I have no clue how to test for this in an automated way.

The only thing preventing `ts-node-dev` from working at this point is the boolean logic at:
https://github.com/fastify/fastify-autoload/blob/master/index.js#L100.
Simply extending the `typescriptSupport` boolean to also check for the `ts-node-dev` environment works perfectly.

Should I go ahead and create a separate issue for writing tests for this?
Maybe the community can help out?

**Comment by fox1t** [comment]
I think this is a needed feature and we should land it as soon as possible. What is not clear to me is why `ts-node.register.instance` is not set in `process`. By the way, we are already missing a test for `ts-node`. 

@MichielDeMey probably testing this would involve running a test file using ts-node and ts-node-dev and checking the variables in `process`/`process.env`.

**Comment by RafaelGSS** [comment]
Sorry for the delay. I agree that's should land as soon and unfortunately, the tests could have a bit of complexity.

However, the `ts-node` should be tested on `npm run typescript:jest`. The problem is that on tests the `ts-node` symbol not exists and `typescriptSupport` is set by:
```js
const typescriptSupport = isTsNode || (isJestEnviroment && hasTsJest /* true */) 
```
And the affirmation of @fox1t: 
> By the way, we are already missing a test for ts-node.

is true.

IMO, we can land this and create an issue to solve both tests

**Comment by mcollina** [comment]
can you folks create such an issue? Thanks.

**Comment by RafaelGSS** [comment]
I created, feel free to update the description if it's not clear.

**Review by RafaelGSS — APPROVED** [review]
LGTM.

**Comment by MichielDeMey** [comment]
> What is not clear to me is why `ts-node.register.instance` is not set in `process`.

I was confused as well and did some digging. They only recently added the environment variable option as a solution to checking if you're running in `ts-node-dev`: https://github.com/whitecolor/ts-node-dev/issues/108.

Setting `ts-node.register.instance` was a proposed solution but it seems they just ended up with an environment variable.
Feel free to re-open the discussion over at their repository to make `ts-node` and `ts-node-dev` more uniform. 🙂

**Comment by jmfury** [comment]
> I was confused as well and did some digging. They only recently added the environment variable option as a solution to checking if you're running in ts-node-dev: wclr/ts-node-dev#108.

:wave:  Just wanted to point out an issue I had getting going (with project using `ts-node-dev`).

The errors I got from `fastify-autoload` while using `ts-node-dev@1.0.0-pre.50` sort of made me question the types & my own module resolution. This was not the case.

Turns out the fix was simply to bump the version to `ts-node-dev@1.1.1`  since it was the *environment variable* missing from this package in that prerelease. 

I think the check for the `process.env.TS_NODE_DEV` is all good, just a rough patch with this dependency. 

I don't think I have the context to contribute a docs/README entry but _minimum versions_ of the dev deps might be good for any future Typescript notes. 

Thought I'd share in case it helps anyone else down the road :smile:

**Comment by mcollina** [comment]
thanks for sharing!

**Pull request merged**
