### PR TITLE
refactor: better support typescript

### PR DESCRIPTION
**Pull request by climba03003**
#### Checklist

- [ ] run `npm run test` and `npm run benchmark`
- [ ] tests and/or benchmarks are included
- [ ] documentation is changed or added
- [ ] commit message and code follows the [Developer's Certification of Origin](https://github.com/fastify/.github/blob/master/CONTRIBUTING.md#developers-certificate-of-origin-11)
      and the [Code of conduct](https://github.com/fastify/.github/blob/master/CODE_OF_CONDUCT.md)

### CODE REVIEW

**Comment by climba03003** [comment]
Double checked the test is failed even in current `master`.

**Comment by mcollina** [comment]
Can you fix it?

**Comment by mcollina** [comment]
Tests are fixed on master

**Comment by climba03003** [comment]
The changes here is `lazy` check typescript environment only when `TypeScript` extension is used.
It support more case like `--loader ts-node/esm`.

**Comment by mcollina** [comment]
Then can you make so? ;)

**Review by mcollina — APPROVED** [review]
lgtm

**Pull request merged**
